#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_END };

enum OBJID { OBJ_PLAYER, OBJ_MOUSE, OBJ_BUTTON, OBJ_MONSTER, OBJ_BULLET, OBJ_SHIELD, OBJ_ITEM, OBJ_NPC, OBJ_PORTAL, OBJ_BLOCK, OBJ_END };

enum MENUOBJID { MENU_CHOOSE, MENU_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT_MENU, SC_EDIT, SC_STAGE_FIELD, 
	SC_STAGE_STORE, SC_STAGE_STOREROOM, SC_STAGE_SHOESTORE,SC_SHOE_MINIGAME,
	SC_STAGE_DUNGEON, SC_STAGE_BOSS, SC_STAGE_ENDING, SC_ENDING_LOGO,
	SC_MINIROAD, SC_MINIWORLD, SC_MINIROOM , SC_MINIROOM2, SC_MINIROOM3, SC_MINIWOOD,
	SC_MINICHIEF, SC_MINIGAME,
	SC_INVEN, SC_QUEST,  SC_END };

enum BLOCKID { BLOCK_GRASS, BLOCK_JAR, BLOCK_CHEST ,BLOCK_FIRE, BLOCK_MUSHROOM, BLOCK_WOOD, BLOCK_SEED, BLOCK_END};

enum BULLETID {BULLET_LASER, BUllET_FIRE, BULLET_MAGIC, BULLET_THUNDER, BULLET_KAGURA, BULLET_END};

enum MONSTERID {SNAKE_MONSTER, OCTOPUS_MONSTER, MOBLIN_MONSTER, ROCK_MONSTER, BOSS_MONSTER, MONSTER_END};

enum ITEMID { ITEM_COIN, ITEM_PORTION, ITEM_HEART, ITEM_KEY, ITEM_STRANGEMAN, ITEM_NOTHING, ITEM_END };

enum WEAPONID { SWORD, WAND, ARROW, SHIELD, LANTON, BOOMERANG, HORSE, WEAPON_END};

enum QUESTID {FIELD_QUEST, STORE_QUEST, MINIQUEST_FLOWER, MINIQUEST_WRITER, MINIQUEST_KEY, QUEST_END};

enum TILEID { TILE_EDIT, TILE_SWITCH, TILE_WALK, TILE_END};

enum CHANNELID { SOUND_BGM, SOUND_EFFECT, PUZZLE_EFFECT ,PLAYER_EFFECT, WALK_EFFECT, MONSTER_EFFECT, MONSTER_BULLET,BUllET_EFFECT, TILE_EFFECT, ITEM_EFFECT, MAXCHANNEL };

enum NPCID { FIELD_NPC, STORE_NPC, SHOE_NPC, MINI_NPC , MINI_NPC2, MINI_NPC3, MINI_CHIEF, MINIWOOD_NPC, NPC_END};

enum RENDERID { RENDER_PLAYERUPOBJECT, RENDER_GAMEOBJECT, RENDER_MONSTER, RENDER_EFFECT, RENDER_PLAYER, RENDER_END };